services:
  - type: web
    name: zazab
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://zazabakery:ktvuWxKbjKBXIxvOjiEyXMxpnpOykWji@dpg-d2lgqjje5dus738qbeg0-a.oregon-postgres.render.com/zazab_vxvf
      - key: SECRET_KEY
        value: zazabakey12345676276
    plan: free
