services:
  - type: web
    name: zazab-bakery
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: zazab
          property: connectionString
      - key: SECRET_KEY
        value: zazab_supersecret123
