services:
  - type: web
    name: zazab
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://zazabakery:ChUPeGlCVnaUytTrHNaLRs0p8RVkoDxS@dpg-d1vahlbuibrs7397vq40-a.oregon-postgres.render.com/zazab
      - key: SECRET_KEY
        value: zazabakey12345676276
    plan: free
